# Generated By: Claude Code (Claude Opus 4.6)

.PHONY: check install install-dev install-no-deps uninstall clean format lint typecheck test test-verbose coverage

# Use shared ~/.venv/ap if it exists, otherwise local .venv
# Support both Unix (bin/python) and Windows (Scripts/python) venv layouts
VENV_DIR ?= $(if $(wildcard $(HOME)/.venv/ap/bin/python),$(HOME)/.venv/ap,$(if $(wildcard $(HOME)/.venv/ap/Scripts/python),$(HOME)/.venv/ap,.venv))
PYTHON = $(if $(wildcard $(VENV_DIR)/Scripts/python),$(VENV_DIR)/Scripts/python,$(VENV_DIR)/bin/python)

$(info venv: $(VENV_DIR))

check: format lint typecheck test coverage

.DEFAULT_GOAL := check

$(PYTHON):
	python -m venv $(VENV_DIR)

install: $(PYTHON)
	$(PYTHON) -m pip install .

install-dev: $(PYTHON)
	$(PYTHON) -m pip install -e ".[dev]"

install-no-deps: $(PYTHON)
	$(PYTHON) -m pip install -e . --no-deps

uninstall:
	$(PYTHON) -m pip uninstall -y mcp-claude-allowlist

clean:
	rm -rf build/ dist/ *.egg-info src/*.egg-info htmlcov/ .coverage coverage.xml
	find . -type d -name __pycache__ -exec rm -r {} + 2>/dev/null || true
	find . -type f -name "*.pyc" -delete 2>/dev/null || true

format: install-dev
	$(PYTHON) -m ruff format src/ tests/

lint: install-dev
	$(PYTHON) -m ruff check src/ tests/

typecheck: install-dev
	$(PYTHON) -m mypy src/

test: install-dev
	$(PYTHON) -m pytest

test-verbose: install-dev
	$(PYTHON) -m pytest -v

coverage: install-dev
	$(PYTHON) -m pytest --cov=src --cov-report=term
