# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for settings module."""

import json
from pathlib import Path
from unittest.mock import patch

from mcp_claude_allowlist.settings import (
    get_all_allowed,
    get_global_allowlist,
    get_local_allowlist,
)


def _write_settings(path: Path, allow_list: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps({"permissions": {"allow": allow_list}}))


class TestGetGlobalAllowlist:
    def test_reads_global_settings(self, tmp_path):
        settings_file = tmp_path / "settings.json"
        _write_settings(settings_file, ["Bash(ls:*)", "WebSearch"])
        with patch("mcp_claude_allowlist.settings.GLOBAL_SETTINGS_PATH", settings_file):
            result = get_global_allowlist()
        assert result == ["Bash(ls:*)", "WebSearch"]

    def test_missing_file_returns_empty(self, tmp_path):
        missing = tmp_path / "nonexistent.json"
        with patch("mcp_claude_allowlist.settings.GLOBAL_SETTINGS_PATH", missing):
            result = get_global_allowlist()
        assert result == []

    def test_no_permissions_key_returns_empty(self, tmp_path):
        settings_file = tmp_path / "settings.json"
        settings_file.write_text(json.dumps({"model": "opus"}))
        with patch("mcp_claude_allowlist.settings.GLOBAL_SETTINGS_PATH", settings_file):
            result = get_global_allowlist()
        assert result == []

    def test_invalid_json_returns_empty(self, tmp_path):
        settings_file = tmp_path / "settings.json"
        settings_file.write_text("not json")
        with patch("mcp_claude_allowlist.settings.GLOBAL_SETTINGS_PATH", settings_file):
            result = get_global_allowlist()
        assert result == []


class TestGetLocalAllowlist:
    def test_reads_both_local_files(self, tmp_path):
        _write_settings(tmp_path / ".claude" / "settings.json", ["Bash(make test:*)"])
        _write_settings(tmp_path / ".claude" / "settings.local.json", ["Bash(ls:*)"])
        result = get_local_allowlist(str(tmp_path))
        assert result["settings"] == ["Bash(make test:*)"]
        assert result["settings_local"] == ["Bash(ls:*)"]
        assert result["merged"] == ["Bash(make test:*)", "Bash(ls:*)"]

    def test_deduplicates_merged(self, tmp_path):
        _write_settings(tmp_path / ".claude" / "settings.json", ["Bash(ls:*)", "WebSearch"])
        _write_settings(tmp_path / ".claude" / "settings.local.json", ["Bash(ls:*)"])
        result = get_local_allowlist(str(tmp_path))
        assert result["merged"] == ["Bash(ls:*)", "WebSearch"]

    def test_missing_files_returns_empty(self, tmp_path):
        result = get_local_allowlist(str(tmp_path))
        assert result["settings"] == []
        assert result["settings_local"] == []
        assert result["merged"] == []


class TestGetAllAllowed:
    def test_merges_global_and_local(self, tmp_path):
        global_file = tmp_path / "global_settings.json"
        _write_settings(global_file, ["Bash(ls:*)", "WebSearch"])
        _write_settings(tmp_path / ".claude" / "settings.json", ["Bash(make test:*)"])

        with patch("mcp_claude_allowlist.settings.GLOBAL_SETTINGS_PATH", global_file):
            result = get_all_allowed(str(tmp_path))

        assert result["global_count"] == 2
        assert result["local_count"] == 1
        assert result["total_count"] == 3
        assert "Bash(ls:*)" in result["permissions"]
        assert "WebSearch" in result["permissions"]
        assert "Bash(make test:*)" in result["permissions"]

    def test_deduplicates_across_global_and_local(self, tmp_path):
        global_file = tmp_path / "global_settings.json"
        _write_settings(global_file, ["Bash(ls:*)", "WebSearch"])
        _write_settings(tmp_path / ".claude" / "settings.json", ["Bash(ls:*)"])

        with patch("mcp_claude_allowlist.settings.GLOBAL_SETTINGS_PATH", global_file):
            result = get_all_allowed(str(tmp_path))

        assert result["total_count"] == 2
        assert result["permissions"] == ["Bash(ls:*)", "WebSearch"]
