# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for MCP server tool handlers."""

import json
from unittest.mock import patch

import pytest

from mcp_claude_allowlist.mcp_server import handle_call_tool, handle_list_tools


class TestListTools:
    @pytest.mark.asyncio
    async def test_returns_three_tools(self):
        tools = await handle_list_tools()
        assert len(tools) == 3
        names = {t.name for t in tools}
        assert names == {
            "get_global_allowed_permissions",
            "get_local_allowed_permissions",
            "get_allowed_permissions",
        }


class TestCallTool:
    @pytest.mark.asyncio
    async def test_global_tool(self):
        with patch(
            "mcp_claude_allowlist.mcp_server.get_global_allowlist",
            return_value=["Bash(ls:*)"],
        ):
            result = await handle_call_tool("get_global_allowed_permissions", None)
        data = json.loads(result[0].text)
        assert data["source"] == "global"
        assert data["permissions"] == ["Bash(ls:*)"]
        assert data["count"] == 1

    @pytest.mark.asyncio
    async def test_local_tool(self):
        mock_data = {
            "project_dir": "/tmp/test",
            "settings": ["Bash(make:*)"],
            "settings_local": [],
            "merged": ["Bash(make:*)"],
        }
        with patch(
            "mcp_claude_allowlist.mcp_server.get_local_allowlist",
            return_value=mock_data,
        ):
            result = await handle_call_tool(
                "get_local_allowed_permissions", {"project_dir": "/tmp/test"}
            )
        data = json.loads(result[0].text)
        assert data["source"] == "local"
        assert data["merged"] == ["Bash(make:*)"]

    @pytest.mark.asyncio
    async def test_merged_tool(self):
        mock_data = {
            "project_dir": "/tmp/test",
            "global_count": 1,
            "local_count": 1,
            "total_count": 2,
            "permissions": ["Bash(ls:*)", "Bash(make:*)"],
        }
        with patch(
            "mcp_claude_allowlist.mcp_server.get_all_allowed",
            return_value=mock_data,
        ):
            result = await handle_call_tool("get_allowed_permissions", {"project_dir": "/tmp/test"})
        data = json.loads(result[0].text)
        assert data["source"] == "merged"
        assert data["total_count"] == 2

    @pytest.mark.asyncio
    async def test_unknown_tool_raises(self):
        with pytest.raises(ValueError, match="Unknown tool"):
            await handle_call_tool("nonexistent", None)
