# Generated By: Claude Code (Claude Opus 4.6)
"""MCP server exposing Claude Code allowed permissions."""

import asyncio
import json
import logging
from datetime import datetime
from typing import Any

from mcp.server import Server
from mcp.server.models import InitializationOptions
from mcp.server.stdio import stdio_server
from mcp.types import TextContent, Tool

from .settings import get_all_allowed, get_global_allowlist, get_local_allowlist

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

server = Server("mcp-claude-allowlist")


def _response(data: dict[str, Any]) -> list[TextContent]:
    data["timestamp"] = datetime.now().isoformat()
    return [TextContent(type="text", text=json.dumps(data, indent=2))]


@server.list_tools()
async def handle_list_tools() -> list[Tool]:
    """List available tools."""
    project_dir_prop = {
        "type": "string",
        "description": "Project directory path. Defaults to current working directory.",
    }
    return [
        Tool(
            name="get_global_allowed_permissions",
            description=(
                "Get the globally allowed permissions from ~/.claude/settings.json. "
                "These are permissions the user has approved across all projects."
            ),
            inputSchema={"type": "object", "properties": {}, "required": []},
        ),
        Tool(
            name="get_local_allowed_permissions",
            description=(
                "Get project-local allowed permissions from .claude/settings.json "
                "and .claude/settings.local.json in the given project directory."
            ),
            inputSchema={
                "type": "object",
                "properties": {"project_dir": project_dir_prop},
                "required": [],
            },
        ),
        Tool(
            name="get_allowed_permissions",
            description=(
                "Get all allowed permissions — a deduplicated merge of global and "
                "project-local permissions. This is the single tool to call when you "
                "want the full picture of what commands are pre-approved."
            ),
            inputSchema={
                "type": "object",
                "properties": {"project_dir": project_dir_prop},
                "required": [],
            },
        ),
    ]


@server.call_tool()
async def handle_call_tool(name: str, arguments: dict[str, Any] | None) -> list[TextContent]:
    """Handle tool calls."""
    args = arguments or {}

    if name == "get_global_allowed_permissions":
        permissions = get_global_allowlist()
        return _response(
            {"source": "global", "count": len(permissions), "permissions": permissions}
        )

    if name == "get_local_allowed_permissions":
        data = get_local_allowlist(args.get("project_dir"))
        return _response({"source": "local", **data})

    if name == "get_allowed_permissions":
        data = get_all_allowed(args.get("project_dir"))
        return _response({"source": "merged", **data})

    raise ValueError(f"Unknown tool: {name}")


async def main() -> None:
    """Run the MCP server."""
    logger.info("Starting MCP Claude Allowlist server...")
    async with stdio_server() as (read_stream, write_stream):
        await server.run(
            read_stream,
            write_stream,
            InitializationOptions(
                server_name="mcp-claude-allowlist",
                server_version="0.1.0",
                capabilities=server.get_capabilities(
                    notification_options=type(
                        "NotificationOptions", (), {"tools_changed": False}
                    )(),
                    experimental_capabilities={},
                ),
            ),
        )


def main_sync() -> None:
    """Synchronous entry point for the MCP server."""
    asyncio.run(main())


if __name__ == "__main__":
    main_sync()
