# Generated By: Claude Code (Claude Opus 4.6)
"""Read Claude Code permission allowlists from settings files."""

import json
import logging
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

GLOBAL_SETTINGS_PATH = Path.home() / ".claude" / "settings.json"


def _read_allow_list(path: Path) -> list[str]:
    """Read permissions.allow from a Claude settings JSON file."""
    if not path.is_file():
        logger.debug("Settings file not found: %s", path)
        return []
    try:
        data = json.loads(path.read_text())
        allow = data.get("permissions", {}).get("allow", [])
        if not isinstance(allow, list):
            logger.warning("permissions.allow is not a list in %s", path)
            return []
        return [str(item) for item in allow]
    except (json.JSONDecodeError, OSError) as e:
        logger.error("Failed to read %s: %s", path, e)
        return []


def get_global_allowlist() -> list[str]:
    """Return the global allow list from ~/.claude/settings.json."""
    return _read_allow_list(GLOBAL_SETTINGS_PATH)


def get_local_allowlist(project_dir: str | None = None) -> dict[str, Any]:
    """Return the project-local allow lists.

    Reads both .claude/settings.json and .claude/settings.local.json from
    the given project directory, returning each list plus a deduplicated merge.
    """
    base = Path(project_dir) if project_dir else Path.cwd()
    settings_path = base / ".claude" / "settings.json"
    local_path = base / ".claude" / "settings.local.json"

    settings_list = _read_allow_list(settings_path)
    local_list = _read_allow_list(local_path)

    # Deduplicated merge preserving order
    seen: set[str] = set()
    merged: list[str] = []
    for item in settings_list + local_list:
        if item not in seen:
            seen.add(item)
            merged.append(item)

    return {
        "project_dir": str(base),
        "settings": settings_list,
        "settings_local": local_list,
        "merged": merged,
    }


def get_all_allowed(project_dir: str | None = None) -> dict[str, Any]:
    """Return deduplicated merge of global + local allow lists."""
    global_list = get_global_allowlist()
    local_data = get_local_allowlist(project_dir)
    local_merged = local_data["merged"]

    seen: set[str] = set()
    merged: list[str] = []
    for item in global_list + local_merged:
        if item not in seen:
            seen.add(item)
            merged.append(item)

    return {
        "project_dir": local_data["project_dir"],
        "global_count": len(global_list),
        "local_count": len(local_merged),
        "total_count": len(merged),
        "permissions": merged,
    }
